/**
 * Centralized Skill Taxonomy & Canonical Registry for PathRecommender
 * Contains recognized technical and professional skills with canonical names, categories, and alias mappings.
 */

const CANONICAL_SKILLS = [
  // ─── Programming Languages ───
  { name: 'JavaScript', category: 'Programming Language', description: 'Dynamic language powering the modern web and Node.js runtimes.' },
  { name: 'TypeScript', category: 'Programming Language', description: 'Typed superset of JavaScript providing static type checking.' },
  { name: 'Python', category: 'Programming Language', description: 'High-level versatile language for web, data science, and AI.' },
  { name: 'Java', category: 'Programming Language', description: 'Object-oriented, class-based language for enterprise backend and Android.' },
  { name: 'C++', category: 'Programming Language', description: 'High-performance compiled language with low-level memory management.' },
  { name: 'C#', category: 'Programming Language', description: 'Modern object-oriented language developed by Microsoft for .NET.' },
  { name: 'C', category: 'Programming Language', description: 'Foundational procedural language for systems programming and embedded devices.' },
  { name: 'Go', category: 'Programming Language', description: 'Statically typed compiled language designed for concurrency and cloud services.' },
  { name: 'Rust', category: 'Programming Language', description: 'Memory-safe systems programming language without garbage collection.' },
  { name: 'PHP', category: 'Programming Language', description: 'Popular server-side scripting language for web development.' },
  { name: 'Ruby', category: 'Programming Language', description: 'Dynamic, object-oriented language focused on simplicity and developer happiness.' },
  { name: 'Swift', category: 'Programming Language', description: 'Modern, fast, and safe language for iOS, macOS, and Apple platforms.' },
  { name: 'Kotlin', category: 'Programming Language', description: 'Modern concise language interoperable with Java, primary for modern Android.' },
  { name: 'R', category: 'Programming Language', description: 'Statistical programming language for data analysis and graphics.' },
  { name: 'Scala', category: 'Programming Language', description: 'Combines object-oriented and functional programming on the JVM.' },
  { name: 'Dart', category: 'Programming Language', description: 'Client-optimized language for fast apps on any platform, powering Flutter.' },
  { name: 'SQL', category: 'Programming Language', description: 'Standard declarative language for relational database management.' },
  { name: 'Bash', category: 'Programming Language', description: 'Unix shell and command language for scripting and automation.' },

  // ─── Frontend Development ───
  { name: 'HTML', category: 'Frontend', description: 'Standard markup language for documents designed to be displayed in web browsers.' },
  { name: 'CSS', category: 'Frontend', description: 'Style sheet language used for describing presentation of HTML documents.' },
  { name: 'React', category: 'Frontend', description: 'Declarative component-based UI library developed by Meta.' },
  { name: 'Angular', category: 'Frontend', description: 'Comprehensive TypeScript-based web application framework by Google.' },
  { name: 'Vue.js', category: 'Frontend', description: 'Progressive JavaScript framework for building user interfaces.' },
  { name: 'Next.js', category: 'Frontend', description: 'React framework enabling server-side rendering, static generation, and full-stack features.' },
  { name: 'Svelte', category: 'Frontend', description: 'Cybernetically enhanced web framework that compiles code into tiny vanilla JS.' },
  { name: 'Tailwind CSS', category: 'Frontend', description: 'Utility-first CSS framework for rapid modern UI development.' },
  { name: 'Bootstrap', category: 'Frontend', description: 'Popular CSS framework for building responsive, mobile-first websites.' },
  { name: 'Redux', category: 'Frontend', description: 'Predictable state container for JavaScript applications.' },
  { name: 'Zustand', category: 'Frontend', description: 'Small, fast, and scalable bearbones state-management solution.' },
  { name: 'Sass', category: 'Frontend', description: 'CSS preprocessor adding variables, nesting, and mixins.' },
  { name: 'Webpack', category: 'Frontend', description: 'Static module bundler for modern JavaScript applications.' },
  { name: 'Vite', category: 'Frontend', description: 'Next-generation frontend tooling with lightning-fast HMR and build.' },
  { name: 'jQuery', category: 'Frontend', description: 'Fast, small, and feature-rich JavaScript DOM manipulation library.' },
  { name: 'Three.js', category: 'Frontend', description: 'JavaScript 3D library using WebGL for interactive 3D graphics in the browser.' },
  { name: 'Web Performance', category: 'Frontend', description: 'Optimizing web pages for loading speed, responsiveness, and Core Web Vitals.' },
  { name: 'Web Accessibility', category: 'Frontend', description: 'Designing web applications accessible to all users including WCAG compliance.' },

  // ─── Backend Development ───
  { name: 'Node.js', category: 'Backend', description: 'Asynchronous event-driven JavaScript runtime built on Chrome\'s V8 engine.' },
  { name: 'Express.js', category: 'Backend', description: 'Fast, unopinionated, minimalist web framework for Node.js.' },
  { name: 'Django', category: 'Backend', description: 'High-level Python web framework encouraging clean, pragmatic design.' },
  { name: 'Flask', category: 'Backend', description: 'Lightweight WSGI Python micro web framework.' },
  { name: 'FastAPI', category: 'Backend', description: 'Modern, high-performance web framework for building APIs with Python 3.8+.' },
  { name: 'Spring Boot', category: 'Backend', description: 'Production-ready framework for building Java stand-alone enterprise services.' },
  { name: 'NestJS', category: 'Backend', description: 'Progressive Node.js framework using TypeScript for building scalable server-side apps.' },
  { name: 'Ruby on Rails', category: 'Backend', description: 'Model-View-Controller framework providing default database and web page structures.' },
  { name: 'ASP.NET Core', category: 'Backend', description: 'Cross-platform, high-performance framework for building modern cloud-connected apps.' },
  { name: 'REST API', category: 'Backend', description: 'Architectural style for networked applications using standard HTTP methods.' },
  { name: 'GraphQL', category: 'Backend', description: 'Query language for APIs and runtime for fulfilling queries with existing data.' },
  { name: 'gRPC', category: 'Backend', description: 'High-performance, open-source universal RPC framework.' },
  { name: 'Socket.io', category: 'Backend', description: 'Bidirectional, low-latency communication library between client and server.' },
  { name: 'Microservices', category: 'Backend', description: 'Architectural design pattern arranging an application as a collection of loosely coupled services.' },
  { name: 'Laravel', category: 'Backend', description: 'PHP web application framework with expressive, elegant syntax.' },

  // ─── Databases ───
  { name: 'MongoDB', category: 'Database', description: 'Source-available, cross-platform document-oriented NoSQL database.' },
  { name: 'PostgreSQL', category: 'Database', description: 'Powerful, open-source object-relational database system.' },
  { name: 'MySQL', category: 'Database', description: 'Open-source relational database management system.' },
  { name: 'Redis', category: 'Database', description: 'In-memory data structure store used as database, cache, and message broker.' },
  { name: 'SQLite', category: 'Database', description: 'C-language library that implements a small, fast, self-contained SQL database engine.' },
  { name: 'Cassandra', category: 'Database', description: 'Distributed wide-column store NoSQL database designed for large volumes of data.' },
  { name: 'DynamoDB', category: 'Database', description: 'Fully managed NoSQL database service from Amazon Web Services.' },
  { name: 'Elasticsearch', category: 'Database', description: 'Distributed, RESTful search and analytics engine for all types of data.' },
  { name: 'Firebase', category: 'Database', description: 'Backend-as-a-Service providing real-time NoSQL database (Firestore) and auth.' },
  { name: 'Supabase', category: 'Database', description: 'Open-source Firebase alternative built on top of PostgreSQL.' },
  { name: 'Oracle Database', category: 'Database', description: 'Multi-model enterprise relational database management system.' },
  { name: 'Neo4j', category: 'Database', description: 'Graph database management system developed by Neo4j, Inc.' },

  // ─── Cloud & DevOps ───
  { name: 'Docker', category: 'Cloud & DevOps', description: 'Platform for developing, shipping, and running applications in lightweight containers.' },
  { name: 'Kubernetes', category: 'Cloud & DevOps', description: 'Open-source system for automating deployment, scaling, and management of containerized apps.' },
  { name: 'AWS', category: 'Cloud & DevOps', description: 'Amazon Web Services comprehensive cloud computing platform.' },
  { name: 'Azure', category: 'Cloud & DevOps', description: 'Microsoft cloud computing platform for application development and deployment.' },
  { name: 'GCP', category: 'Cloud & DevOps', description: 'Google Cloud Platform suite of cloud computing services.' },
  { name: 'Terraform', category: 'Cloud & DevOps', description: 'Infrastructure as Code software tool that lets you build, change, and version cloud resources.' },
  { name: 'Ansible', category: 'Cloud & DevOps', description: 'Open-source IT automation tool for configuration management and application deployment.' },
  { name: 'CI/CD', category: 'Cloud & DevOps', description: 'Continuous Integration and Continuous Delivery/Deployment automation practices.' },
  { name: 'GitHub Actions', category: 'Cloud & DevOps', description: 'Automated CI/CD pipeline integrated directly into GitHub repositories.' },
  { name: 'Linux', category: 'Cloud & DevOps', description: 'Open-source Unix-like operating system powering servers and cloud containers.' },
  { name: 'Nginx', category: 'Cloud & DevOps', description: 'High-performance web server, reverse proxy, load balancer, and HTTP cache.' },
  { name: 'Apache HTTP Server', category: 'Cloud & DevOps', description: 'Cross-platform open-source web server software.' },
  { name: 'Jenkins', category: 'Cloud & DevOps', description: 'Open-source automation server enabling developers to reliably build and test software.' },
  { name: 'Prometheus', category: 'Cloud & DevOps', description: 'Open-source systems monitoring and alerting toolkit.' },
  { name: 'Grafana', category: 'Cloud & DevOps', description: 'Multi-platform analytics and interactive visualization web application.' },

  // ─── Data Science & AI ───
  { name: 'Machine Learning', category: 'Data & AI', description: 'Field of study focusing on algorithms that learn patterns from data.' },
  { name: 'Deep Learning', category: 'Data & AI', description: 'Subset of machine learning based on artificial multi-layer neural networks.' },
  { name: 'TensorFlow', category: 'Data & AI', description: 'Open-source end-to-end machine learning platform developed by Google.' },
  { name: 'PyTorch', category: 'Data & AI', description: 'Optimized tensor library for deep learning using GPUs and CPUs, developed by Meta.' },
  { name: 'Pandas', category: 'Data & AI', description: 'Fast, powerful, and flexible open-source data analysis and manipulation library for Python.' },
  { name: 'NumPy', category: 'Data & AI', description: 'Fundamental package for scientific computing with Python supporting multi-dimensional arrays.' },
  { name: 'Scikit-learn', category: 'Data & AI', description: 'Simple and efficient tools for predictive data analysis built on NumPy and SciPy.' },
  { name: 'LangChain', category: 'Data & AI', description: 'Framework for developing applications powered by language models and agent workflows.' },
  { name: 'LlamaIndex', category: 'Data & AI', description: 'Data framework for LLM-based applications to ingest, structure, and access private data.' },
  { name: 'Natural Language Processing', category: 'Data & AI', description: 'Techniques for analyzing, understanding, and generating human language.' },
  { name: 'Computer Vision', category: 'Data & AI', description: 'Field of artificial intelligence enabling computers to derive meaningful info from images/videos.' },
  { name: 'OpenCV', category: 'Data & AI', description: 'Open-source computer vision and machine learning software library.' },
  { name: 'Keras', category: 'Data & AI', description: 'High-level neural networks API, written in Python and capable of running on top of TensorFlow.' },
  { name: 'Generative AI', category: 'Data & AI', description: 'Artificial intelligence capable of generating text, images, or other data using generative models.' },
  { name: 'Hugging Face', category: 'Data & AI', description: 'Platform and library ecosystem for state-of-the-art open-source machine learning models.' },

  // ─── Architecture & System Design ───
  { name: 'System Design', category: 'Architecture & System Design', description: 'Process of defining architecture, components, modules, interfaces, and data for large-scale systems.' },
  { name: 'Distributed Systems', category: 'Architecture & System Design', description: 'Systems whose components are located on different networked computers communicating via messages.' },
  { name: 'Load Balancing', category: 'Architecture & System Design', description: 'Distributing incoming network traffic across multiple servers to ensure reliability and speed.' },
  { name: 'Caching', category: 'Architecture & System Design', description: 'Storing copies of data in temporary storage locations for rapid access.' },
  { name: 'Message Queues', category: 'Architecture & System Design', description: 'Asynchronous service-to-service communication mechanisms used in serverless and microservice architectures.' },
  { name: 'Apache Kafka', category: 'Architecture & System Design', description: 'Distributed event store and stream-processing platform.' },
  { name: 'RabbitMQ', category: 'Architecture & System Design', description: 'Widely deployed open-source message broker.' },

  // ─── Testing & Quality Assurance ───
  { name: 'Unit Testing', category: 'Testing & QA', description: 'Testing individual units or components of a software application.' },
  { name: 'Integration Testing', category: 'Testing & QA', description: 'Phase in software testing where individual software modules are combined and tested as a group.' },
  { name: 'Jest', category: 'Testing & QA', description: 'Delightful JavaScript Testing Framework with a focus on simplicity.' },
  { name: 'React Testing Library', category: 'Testing & QA', description: 'Lightweight solution for testing React components matching user interactions.' },
  { name: 'Cypress', category: 'Testing & QA', description: 'Next generation front end testing tool built for the modern web.' },
  { name: 'Playwright', category: 'Testing & QA', description: 'Framework for Web Testing and Automation across Chromium, Firefox, and WebKit.' },
  { name: 'Selenium', category: 'Testing & QA', description: 'Portable framework for testing web applications.' },

  // ─── Security & Authentication ───
  { name: 'Authentication', category: 'Security', description: 'Verifying identity of users via credentials, sessions, tokens, or SSO.' },
  { name: 'JWT', category: 'Security', description: 'JSON Web Tokens for securely transmitting information between parties as a JSON object.' },
  { name: 'OAuth 2.0', category: 'Security', description: 'Industry-standard protocol for authorization and third-party login integration.' },
  { name: 'Web Security', category: 'Security', description: 'Defending web applications from vulnerabilities including XSS, CSRF, SQL Injection, and CORS issues.' },

  // ─── Design, Tools & Professional Skills ───
  { name: 'Photoshop', category: 'Design & Creative', description: 'Industry-standard raster graphics editor developed by Adobe.' },
  { name: 'Figma', category: 'Design & Creative', description: 'Collaborative cloud-based interface design and prototyping tool.' },
  { name: 'Adobe Illustrator', category: 'Design & Creative', description: 'Vector graphics editor and design program developed by Adobe.' },
  { name: 'Git', category: 'Developer Tools', description: 'Distributed version control system for tracking changes in source code.' },
  { name: 'GitHub', category: 'Developer Tools', description: 'Cloud hosting platform for version control and collaborative software development.' },
  { name: 'Postman', category: 'Developer Tools', description: 'API platform for building and using APIs and automated endpoint testing.' },
  { name: 'Jira', category: 'Developer Tools', description: 'Agile project management and issue tracking tool developed by Atlassian.' },
  { name: 'Data Structures', category: 'Computer Science', description: 'Ways of organizing and storing data in computer memory (Arrays, Trees, Graphs, Hash Maps).' },
  { name: 'Algorithms', category: 'Computer Science', description: 'Step-by-step procedures for calculation, data processing, and automated reasoning.' },
  { name: 'Object-Oriented Programming', category: 'Computer Science', description: 'Programming paradigm based on the concept of objects containing data and code.' }
];

/**
 * Normalization helper: strips whitespace, punctuation, dashes, underscores, and lowercases.
 */
const normalizeSkillKey = (str) => {
  return (str || '').toLowerCase().trim().replace(/[^a-z0-9]/g, '');
};

/**
 * Alias and common variant mapping to Canonical Skill Names.
 */
const SKILL_ALIASES = {
  // JavaScript & TypeScript
  'js': 'JavaScript',
  'javascript': 'JavaScript',
  'javascriptes6': 'JavaScript',
  'es6': 'JavaScript',
  'vanillajs': 'JavaScript',
  'ecmascript': 'JavaScript',
  'ts': 'TypeScript',
  'typescript': 'TypeScript',

  // Python
  'py': 'Python',
  'python': 'Python',
  'python3': 'Python',
  'py3': 'Python',

  // Java & C Languages
  'java': 'Java',
  'corejava': 'Java',
  'c': 'C',
  'clang': 'C',
  'clanguage': 'C',
  'cpp': 'C++',
  'cplusplus': 'C++',
  'cplus': 'C++',
  'csharp': 'C#',
  'cs': 'C#',
  'c#': 'C#',
  'dotnet': 'C#',

  // Go, Rust, PHP, Ruby, etc.
  'go': 'Go',
  'golang': 'Go',
  'rust': 'Rust',
  'rustlang': 'Rust',
  'php': 'PHP',
  'php8': 'PHP',
  'ruby': 'Ruby',
  'rubylang': 'Ruby',
  'swift': 'Swift',
  'swiftlang': 'Swift',
  'kotlin': 'Kotlin',
  'dart': 'Dart',
  'dartlang': 'Dart',
  'scala': 'Scala',
  'r': 'R',
  'rlang': 'R',
  'bash': 'Bash',
  'shell': 'Bash',
  'shellscripting': 'Bash',

  // Frontend
  'html': 'HTML',
  'html5': 'HTML',
  'htm': 'HTML',
  'css': 'CSS',
  'css3': 'CSS',
  'htmlcss': 'HTML',
  'react': 'React',
  'reactjs': 'React',
  'react.js': 'React',
  'reactnative': 'React',
  'angular': 'Angular',
  'angularjs': 'Angular',
  'angular2': 'Angular',
  'vue': 'Vue.js',
  'vuejs': 'Vue.js',
  'vue.js': 'Vue.js',
  'next': 'Next.js',
  'nextjs': 'Next.js',
  'next.js': 'Next.js',
  'svelte': 'Svelte',
  'sveltejs': 'Svelte',
  'tailwind': 'Tailwind CSS',
  'tailwindcss': 'Tailwind CSS',
  'bootstrap': 'Bootstrap',
  'bootstrap5': 'Bootstrap',
  'redux': 'Redux',
  'reduxtoolkit': 'Redux',
  'rtk': 'Redux',
  'zustand': 'Zustand',
  'sass': 'Sass',
  'scss': 'Sass',
  'webpack': 'Webpack',
  'vite': 'Vite',
  'vitejs': 'Vite',
  'jquery': 'jQuery',
  'threejs': 'Three.js',
  'three.js': 'Three.js',
  'webperf': 'Web Performance',
  'webperformance': 'Web Performance',
  'a11y': 'Web Accessibility',
  'accessibility': 'Web Accessibility',

  // Backend
  'node': 'Node.js',
  'nodejs': 'Node.js',
  'node.js': 'Node.js',
  'node js': 'Node.js',
  'express': 'Express.js',
  'expressjs': 'Express.js',
  'express.js': 'Express.js',
  'django': 'Django',
  'djangorestframework': 'Django',
  'drf': 'Django',
  'flask': 'Flask',
  'fastapi': 'FastAPI',
  'spring': 'Spring Boot',
  'springboot': 'Spring Boot',
  'springmvc': 'Spring Boot',
  'nest': 'NestJS',
  'nestjs': 'NestJS',
  'nest.js': 'NestJS',
  'rails': 'Ruby on Rails',
  'rubyonrails': 'Ruby on Rails',
  'ror': 'Ruby on Rails',
  'aspnet': 'ASP.NET Core',
  'aspnetcore': 'ASP.NET Core',
  'rest': 'REST API',
  'restapi': 'REST API',
  'restapis': 'REST API',
  'restful': 'REST API',
  'restfulapi': 'REST API',
  'graphql': 'GraphQL',
  'gql': 'GraphQL',
  'grpc': 'gRPC',
  'socketio': 'Socket.io',
  'websockets': 'Socket.io',
  'websocket': 'Socket.io',
  'microservices': 'Microservices',
  'microservice': 'Microservices',
  'laravel': 'Laravel',

  // Databases
  'mongo': 'MongoDB',
  'mongodb': 'MongoDB',
  'mongoose': 'MongoDB',
  'postgres': 'PostgreSQL',
  'postgresql': 'PostgreSQL',
  'psql': 'PostgreSQL',
  'postgressql': 'PostgreSQL',
  'mysql': 'MySQL',
  'sqlserver': 'SQL',
  'mssql': 'SQL',
  'redis': 'Redis',
  'sqlite': 'SQLite',
  'sqlite3': 'SQLite',
  'cassandra': 'Cassandra',
  'dynamodb': 'DynamoDB',
  'dynamo': 'DynamoDB',
  'elastic': 'Elasticsearch',
  'elasticsearch': 'Elasticsearch',
  'firebase': 'Firebase',
  'firestore': 'Firebase',
  'supabase': 'Supabase',
  'oracle': 'Oracle Database',
  'oracledb': 'Oracle Database',
  'neo4j': 'Neo4j',

  // Cloud & DevOps
  'docker': 'Docker',
  'dockercompose': 'Docker',
  'k8s': 'Kubernetes',
  'kubernetes': 'Kubernetes',
  'kube': 'Kubernetes',
  'aws': 'AWS',
  'amazonwebservices': 'AWS',
  'awsec2': 'AWS',
  'awss3': 'AWS',
  'awslambda': 'AWS',
  'azure': 'Azure',
  'msazure': 'Azure',
  'microsoftazure': 'Azure',
  'gcp': 'GCP',
  'googlecloud': 'GCP',
  'googlecloudplatform': 'GCP',
  'terraform': 'Terraform',
  'ansible': 'Ansible',
  'cicd': 'CI/CD',
  'continuousintegration': 'CI/CD',
  'githubactions': 'GitHub Actions',
  'actions': 'GitHub Actions',
  'linux': 'Linux',
  'ubuntu': 'Linux',
  'centos': 'Linux',
  'unix': 'Linux',
  'nginx': 'Nginx',
  'apache': 'Apache HTTP Server',
  'apachehttp': 'Apache HTTP Server',
  'jenkins': 'Jenkins',
  'prometheus': 'Prometheus',
  'grafana': 'Grafana',

  // Data Science & AI
  'ml': 'Machine Learning',
  'machinelearning': 'Machine Learning',
  'dl': 'Deep Learning',
  'deeplearning': 'Deep Learning',
  'tf': 'TensorFlow',
  'tensorflow': 'TensorFlow',
  'pytorch': 'PyTorch',
  'torch': 'PyTorch',
  'pandas': 'Pandas',
  'numpy': 'NumPy',
  'scikit': 'Scikit-learn',
  'scikitlearn': 'Scikit-learn',
  'sklearn': 'Scikit-learn',
  'langchain': 'LangChain',
  'llamaindex': 'LlamaIndex',
  'nlp': 'Natural Language Processing',
  'naturallanguageprocessing': 'Natural Language Processing',
  'computervision': 'Computer Vision',
  'cv': 'Computer Vision',
  'opencv': 'OpenCV',
  'keras': 'Keras',
  'genai': 'Generative AI',
  'generativeai': 'Generative AI',
  'llm': 'Generative AI',
  'llms': 'Generative AI',
  'huggingface': 'Hugging Face',
  'transformers': 'Hugging Face',

  // System Design
  'systemdesign': 'System Design',
  'sysdesign': 'System Design',
  'distributedsystems': 'Distributed Systems',
  'loadbalancing': 'Load Balancing',
  'loadbalancer': 'Load Balancing',
  'caching': 'Caching',
  'messagequeue': 'Message Queues',
  'messagequeues': 'Message Queues',
  'mq': 'Message Queues',
  'kafka': 'Apache Kafka',
  'apachekafka': 'Apache Kafka',
  'rabbitmq': 'RabbitMQ',

  // Testing
  'unittesting': 'Unit Testing',
  'unittest': 'Unit Testing',
  'integrationtesting': 'Integration Testing',
  'jest': 'Jest',
  'jestjs': 'Jest',
  'reacttestinglibrary': 'React Testing Library',
  'rtl': 'React Testing Library',
  'cypress': 'Cypress',
  'cypressio': 'Cypress',
  'playwright': 'Playwright',
  'selenium': 'Selenium',
  'seleniumwebdriver': 'Selenium',

  // Security
  'auth': 'Authentication',
  'authentication': 'Authentication',
  'authn': 'Authentication',
  'authz': 'Authentication',
  'jwt': 'JWT',
  'jsonwebtokens': 'JWT',
  'oauth': 'OAuth 2.0',
  'oauth2': 'OAuth 2.0',
  'websecurity': 'Web Security',
  'appsecurity': 'Web Security',

  // Creative & Tools
  'photoshop': 'Photoshop',
  'adobephotoshop': 'Photoshop',
  'ps': 'Photoshop',
  'figma': 'Figma',
  'illustrator': 'Adobe Illustrator',
  'adobeillustrator': 'Adobe Illustrator',
  'ai': 'Adobe Illustrator',
  'git': 'Git',
  'github': 'GitHub',
  'postman': 'Postman',
  'jira': 'Jira',
  'datastructures': 'Data Structures',
  'dsa': 'Data Structures',
  'algorithms': 'Algorithms',
  'algo': 'Algorithms',
  'oop': 'Object-Oriented Programming',
  'oops': 'Object-Oriented Programming'
};

// Build canonical lookup map
const CANONICAL_MAP = new Map();
CANONICAL_SKILLS.forEach(skill => {
  const norm = normalizeSkillKey(skill.name);
  CANONICAL_MAP.set(norm, skill);
  // Also register self in aliases
  if (!SKILL_ALIASES[norm]) {
    SKILL_ALIASES[norm] = skill.name;
  }
});

module.exports = {
  CANONICAL_SKILLS,
  SKILL_ALIASES,
  CANONICAL_MAP,
  normalizeSkillKey
};
